name: Deploy
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.0
      - run: pnpm install
      - name: Build
        run: pnpm run docs:build
      - name: Deploy vitepress docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # 要部署的文件夹 (最终会被拷贝到 gh-pages 分支下)
          folder: ./dist
          # 部署的分支，默认 gh-pages
          branch: gh-pages
          token: ${{ secrets.THE_TOKEN }}
  
